# Generated by psp (https://github.com/MatteoGuadrini/psp), version 0.2.0

FROM python:alpine

# Install dependencies
RUN apk add git 

# Django global variables
ENV DJANGO_SUPERUSER_PASSWORD="Admin000!"
ENV DJANGO_SUPERUSER_USERNAME="adminbb"
ENV DJANGO_SUPERUSER_EMAIL="adminbb@bbweb.com"
ENV BBWEB_CATALOG="/tmp/backup"

# Copy the Python package
COPY butterfly-backup-web /butterfly-backup-web/butterfly-backup-web
COPY pyproject.toml /butterfly-backup-web
WORKDIR /butterfly-backup-web

# Install dependencies
RUN pip install .

# Create Django software structure
RUN python -m butterfly-backup-web migrate && \
    python -m butterfly-backup-web createsuperuser --no-input

# Safe user
RUN adduser --disabled-password butterfly-backup-web_user
USER butterfly-backup-web_user

# Run package
CMD python -m butterfly-backup-web runserver 127.0.0.1:8080
