# Generated by psp (https://github.com/MatteoGuadrini/psp), version 0.2.0

FROM python:alpine

# Copy the Python package
COPY butterfly-backup-web /butterfly-backup-web/butterfly-backup-web
COPY pyproject.toml /butterfly-backup-web
WORKDIR /butterfly-backup-web

# Install dependencies
RUN pip install .

# Safe user
RUN adduser --disabled-password butterfly-backup-web_user
USER butterfly-backup-web_user

# Run package
CMD python -m butterfly-backup-web runserver
