# Generated by psp (https://github.com/MatteoGuadrini/psp), version 0.2.0

PYTHON = python3
VENV = venv

.PHONY: help run clean build deploy

help:
	@echo 'help: make (help|run|clean|build|deploy)'

build:
ifneq ('$(wildcard ${VENV}/bin/${PYTHON})','')
	${VENV}/bin/${PYTHON} -m build
else
	${PYTHON} -m build
endif

deploy:
ifneq ('$(wildcard ${VENV}/bin/${PYTHON})','')
	${VENV}/bin/${PYTHON} -m twine upload dist/*
else
	${PYTHON} -m twine upload dist/*
endif

run:
ifneq ('$(wildcard ${VENV}/bin/${PYTHON})','')
	${VENV}/bin/${PYTHON} -m butterfly-backup-web
else
	${PYTHON} -m butterfly-backup-web
endif

clean:
	rm -fr build/
	rm -fr dist/
	rm -fr .eggs/
	find . -name '*.egg-info' -exec rm -fr {} +
	find . -name '*.egg' -exec rm -f {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -fr {} +
