#! /usr/bin/env python3
# -*- encoding: utf-8 -*-
# vim: se ts=4 et syn=python:
# Generated by psp (https://github.com/MatteoGuadrini/psp), version 0.2.0

from .__init__ import __version__

print('name: butterfly-backup-web ')
print(f'version: {__version__}')
