#! /usr/bin/env python3
# -*- encoding: utf-8 -*-
# vim: se ts=4 et syn=python:
# Generated by psp (https://github.com/MatteoGuadrini/psp), version 0.2.0

import os
import sys

from .__init__ import __version__
from .manage import main


print("name: butterfly-backup-web")
print(f"version: {__version__}")

if __name__ == "__main__":
    sys.path.append(os.path.join(os.getcwd(), "butterfly_backup_web"))
    main()
