"""
Django settings for bbweb project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from os import environ, uname
from importlib.util import find_spec

# Butterfly Backup catalog
CATALOG_PATH = Path(environ.get("BB_CATALOG_PATH", "/tmp/backup"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ne)d_cm&rh5mhll!pgasazhbpa_pzq*#w7dp!gc_7ztrtyy4@u"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [uname().nodename, "localhost", "127.0.0.1"]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bootstrap5",
]

LOCAL_APP = (
    "butterfly_backup_web.bbweb" if find_spec("butterfly_backup_web") else "bbweb"
)
try:
    static_index = INSTALLED_APPS.index("django.contrib.staticfiles")
except ValueError:
    INSTALLED_APPS.append(LOCAL_APP)
else:
    INSTALLED_APPS.insert(static_index, LOCAL_APP)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = (
    "butterfly_backup_web.bbweb.urls"
    if find_spec("butterfly_backup_web")
    else "bbweb.urls"
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = (
    "butterfly_backup_web.bbweb.wsgi.application"
    if find_spec("butterfly_backup_web")
    else "bbweb.wsgi.application"
)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": CATALOG_PATH / "bbweb.db",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

BBWEB_SSL_ENABLE = environ.get("BBWEB_SSL_ENABLE", "False").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
BBWEB_SSL_CERTIFICATE_PATH = environ.get("BBWEB_SSL_CERTIFICATE_PATH")
BBWEB_SSL_KEY_PATH = environ.get("BBWEB_SSL_KEY_PATH")
BBWEB_SSL_CA_CERTIFICATE_PATH = environ.get("BBWEB_SSL_CA_CERTIFICATE_PATH")

if BBWEB_SSL_ENABLE:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(environ.get("BBWEB_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = environ.get(
        "BBWEB_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"
    ).strip().lower() in ("1", "true", "yes", "on")
    SECURE_HSTS_PRELOAD = environ.get(
        "BBWEB_SECURE_HSTS_PRELOAD", "True"
    ).strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    )
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 180
SESSION_SAVE_EVERY_REQUEST = True
